/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

var fibArray = [1, 2];
var ceiling = 4000000;
var total = 0;

for (i = 0; fibArray[fibArray.length - 1] <= 4000000; i++) {
  fibArray.push(fibArray[0 + i] + fibArray[1 + i]);
}

for (i = 0; i < fibArray.length; i++) {
  if (fibArray[i] < 4000000 && fibArray[i] % 2 === 0)
  total = total + fibArray[i];
}

console.log(total);

// 4613732