/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var fibonacciArray = [1, 2];
var ceiling = 4000000;
var total = 0;

for (i = 0; fibonacciArray[fibonacciArray.length - 1] <= 4000000; i++) {
  fibonacciArray.push(fibonacciArray[0 + i] + fibonacciArray[1 + i]);
}

for (i = 0; i < fibonacciArray.length; i++) {
  if (fibonacciArray[i] < 4000000 && fibonacciArray[i] % 2 === 0)
  total = total + fibonacciArray[i];
}

console.log(total);

// 4613732